// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvrvXXbiCrAChozS0-PdgCbl8fB6qt_g',
    appId: '1:360867768638:web:5b07c13fec91ae6c7e246f',
    messagingSenderId: '360867768638',
    projectId: 'sentinel-tanod-system',
    authDomain: 'sentinel-tanod-system.firebaseapp.com',
    databaseURL: 'https://sentinel-tanod-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sentinel-tanod-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLSDKauEB28xoliaUG_hoIYXotBNfujlk',
    appId: '1:360867768638:android:0ee89ffecacda1ee7e246f',
    messagingSenderId: '360867768638',
    projectId: 'sentinel-tanod-system',
    databaseURL: 'https://sentinel-tanod-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sentinel-tanod-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsuzIdDdOMP_ytlJ0rbepOCRbYjUjxnQ',
    appId: '1:360867768638:ios:ba079813a90af5437e246f',
    messagingSenderId: '360867768638',
    projectId: 'sentinel-tanod-system',
    databaseURL: 'https://sentinel-tanod-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sentinel-tanod-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}